// Authentication
export const UPDATE_AUTH = 'UPDATE_AUTH';
export const RESET_AUTH = 'RESET_AUTH';
export const OPEN_AUTHENTICATION_DIALOG = 'OPEN_AUTHENTICATION_DIALOG';
export const TOGGLE_AUTHENTICATION_DIALOG = 'TOGGLE_AUTHENTICATION_DIALOG';
export const CLOSE_AUTHENTICATION_DIALOG = 'CLOSE_AUTHENTICATION_DIALOG';
export const SAVE_REDIRECT_LOCATION = 'SAVE_REDIRECT_LOCATION';
export const UPDATE_USER_SETTINGS = 'UPDATE_USER_SETTINGS';

// resource relation model

export const INITIALIZE_RESOURCE_RELATION_MODEL = 'INITIALIZE_RESOURCE_RELATION_MODEL';
